### ISSUE TITLE
Posible error despues de esta linea

### ISSUE THREAD

**Issue by jesusbibieca** [poptart-o/Domino_project#1]
https://github.com/poptart-o/Domino_project/blob/ba93a2c2946b49456444badcb22348d0f270fce4/domino_project.py#L34

Hey, en este **`if`** estas revisando si la caja esta vacia o no y esta bien hecho con ese if, pero ese if se va a ejecutar solo si esta vacia (eso debe hacer), pero cuando el se ejecute lo que sigue se va a ejecutar sin importar si esta vacio o no. 

https://github.com/poptart-o/Domino_project/blob/ba93a2c2946b49456444badcb22348d0f270fce4/domino_project.py#L36

Esta parte deberia esta en un **`else`** para que solo se ejecute si caja no esta vacia.

```python
if len(self.caja) == 0:
    print 'No hay fichas en la caja'
else:
    for ficha in self.caja:
            print [ficha.value1, ficha.value2]
```

**Comment by poptart-o** [comment]
check
